### ISSUE TITLE
Bikeshed: sbt plugin should be named after the project

### ISSUE THREAD

**Issue by djspiewak** [typelevel/feral#112]
So like, sbt-feral imo rather than sbt-lambda (or sbt-cats-serverless if we change the name).

**Comment by armanbilge** [comment]
So it's currently published as `sbt-feral-lambda`, I assumed it should be specific to each cloud but whatever works :)
https://search.maven.org/artifact/org.typelevel/sbt-feral-lambda

**Comment by djspiewak** [comment]
> So it's currently published as sbt-feral-lambda, I assumed it should be specific to each cloud but whatever works :)

Ah that's an interesting point. Agreed.
