### ISSUE TITLE
Use context function for handler in Scala 3?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/feral#121]
TIL about [context functions](https://docs.scala-lang.org/scala3/reference/contextual/context-functions.html). H/t @som-snytt.

They are new in Scala 3, and provide a `?=>` syntax for anonymous functions using implicit (aka context) parameters. This is exactly our setup with `LambdaEnv`. Not only would this let Scala 3 users skip the boilerplate `implicit env =>`, there seems to be no Scala 3 equivalent of making a non-context parameter into a `given`; see https://github.com/lampepfl/dotty/issues/14167.

Doing this will require splitting our sources on the Scala 2/3 axis in addition to the JVM/JS axis 😩

**Comment by ChristopherDavenport** [comment]
If you do this for yourself you will basically ban cross-compiling platforms or folks that still use implicits. Not something I'd recommend.

Scala 3 only features will drive out those who can't follow your cross.

**Comment by armanbilge** [comment]
> If you do this for yourself you will basically ban cross-compiling platforms or folks that still use implicits.

I'm fairly certain context parameters are compatible with implicit parameters. So I don't think it would be this extreme.

> Scala 3 only features will drive out those who can't follow your cross.

This is a valid concern.

I think this is an interesting case because the code in question is essentially our equivalent of a main method i.e. something that will only exist in applications, not libraries, and thus not subject to the usual degree of crossing. This change shouldn't affect any other code. So I think we could make it work—the burden would be on us really, to maintain two versions of `IOLambda` and two versions of all the examples.

**Comment by ChristopherDavenport** [comment]
If you are certain that no one can abstract the layer you are working at, then it can work. But I know I'm always surprised by the new abstractions that are found, and this is still relatively new.

**Comment by armanbilge** [comment]
Ah, you are completely right. We ourselves are actually currently abstracting this layer in https://github.com/typelevel/feral/pull/89. So any changes here would propagate there, and I don't want to maintain all that. Yeah, this is unfortunately unrealistic/impractical.

**Comment by armanbilge** [comment]
Thanks for the good advice @ChristopherDavenport.
