### ISSUE TITLE
Lambda output empty with 1.0.0-M1

### ISSUE THREAD

**Issue by skirsdeda** [typelevel/feral#226]
First of all, this is a great project! And I love the name :)

When using 1.0.0-M1 I get empty output from lambda (Scala 2.13 compiled for JVM 11). Tried downgrading to 0.1.0-M8 and that one works perfectly fine. Could it be that this commit broke the output?: da29dc72c033c2e37716f58a55786f977352ceb1

**Comment by armanbilge** [comment]
Thanks for the report. Do you have the same issue in `0.1.0-M9`?

**Comment by armanbilge** [comment]
Thanks for confirming! I'll take a closer look a bit later :)
