### ISSUE TITLE
Giter8 Template(s)

### ISSUE THREAD

**Issue by bpholt** [typelevel/feral#251]
It'd be nice to be able to `sbt new {feral variant}` :-)

**Comment by armanbilge** [comment]
Yes! This was described in the original concept :)
https://gist.github.com/djspiewak/37a4ea0d7a5237144ec8b56a76ed080d#onboarding

**Comment by bpholt** [comment]
Oh yeah, I thought we had talked about it somewhere! I couldn't find it in an issue, but I wanted to track it.

**Comment by abhishekshree** [comment]
I want to work on this issue if it's still open for solutions

**Comment by armanbilge** [comment]
@abhishekshree yes please! Thanks for volunteering :)

**Comment by TonioGela** [comment]
I think this can be closed as we now have https://github.com/typelevel/feral.g8
