### ISSUE TITLE
feral example code Http4sLambda.scala does not work for JVM in AWS Lambda

### ISSUE THREAD

**Issue by vivekgupta-cse** [typelevel/feral#382]
I tried to deploy the example code "Http4sLambda.scala " on AWS lambda. After deploying to lambda, and setting it up with API Gateway, I tried to call API  "<url>/foo". It should return the string "bar", but it returns empty response.
I get Response status as 200, but this is how the header contents look like:

Date - Fri, 14 Jul 2023 12:58:19 GMT
Content-Type - application/json
Content-Length - 0
Connection - keep-alive
x-amzn-RequestId- 6ac720.......
x-amz-apigw-id - IDfwg......
X-Amzn-Trace-Id - Root= 1-64b14......

I also tried to add print statements, but nothing get printed in logs. This is the code that I used:
https://github.com/typelevel/feral/blob/main/examples/src/main/scala/feral/examples/Http4sLambda.scala

Later, I was able to successfully run my APIs using this library:
https://github.com/wfaler/http4s-lambda

Same lambda, same API Gateway, only jar is replaced. So this is a bug in either feral itself. It is not working for JVM code.

Java version I used: 17
Scala version: 2.13.11

**Comment by armanbilge** [comment]
> Later, I was able to successfully run my APIs using this library:

That library is using a legacy 1.0 version of the API proxy event. Feral uses the 2.0 version of the API proxy event. Further reading:

https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

**Comment by vivekgupta-cse** [comment]
Hi, I have created a new API Gateway with version 2.0 of API proxy event, and used for the same. Still getting the same issue.

This is the json data that actually reaches the lambda via API Gateway (I deliberately masked some data due to privacy reasons), but there is no change in behaviour

{
    "version": "2.0",
    "routeKey": "ANY /{proxy+}",
    "rawPath": "/dev/foo",
    "rawQueryString": "",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate, br",
        "cache-control": "no-cache",
        "content-length": "0",
        "host": "w4xxxxxxxxx.execute-api.us-east-1.amazonaws.com",
        "postman-token": "faf184bf-72ef-41e5-a0a6-xxxxxxxxxxxx",
        "user-agent": "PostmanRuntime/7.32.3",
        "x-amzn-trace-id": "Root=1-64b6b2bd-1e09a316xxxxxxxxxxxxx",
        "x-forwarded-for": "68.xxx.xxx.xxx",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https"
    },
    "requestContext": {
        "accountId": "007XXXXXXXXXXX",
        "apiId": "w45xxxxxxxxx",
        "domainName": "w45xxxxxxxxx.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "w45xxxxxxxxx",
        "http": {
            "method": "GET",
            "path": "/dev/foo",
            "protocol": "HTTP/1.1",
            "sourceIp": "68.xxx.xxx.xxx",
            "userAgent": "PostmanRuntime/7.32.3"
        },
        "requestId": "IRDdlgxxxxxxxxx=",
        "routeKey": "ANY /{proxy+}",
        "stage": "dev",
        "time": "18/Jul/2023:15:41:49 +0000",
        "timeEpoch": 1689694909006
    },
    "pathParameters": {
        "proxy": "foo"
    },
    "isBase64Encoded": false
}
