### ISSUE TITLE
MiMa Configuration

### ISSUE THREAD

**Issue by bpholt** [typelevel/feral#457]
Is MiMa set up correctly in this build? I briefly looked at #456 this evening and wanted to confirm that MiMa enabled, and I'm getting empty `mimaPreviousArtifacts` values, which I thought was surprising.

```
sbt:feral> show mimaPreviousArtifacts
[info] scalafix-output / mimaPreviousArtifacts
[info] 	Set()
[info] lambdaJVM / mimaPreviousArtifacts
[info] 	Set()
[info] lambdaCloudFormationCustomResourceJS / mimaPreviousArtifacts
[info] 	Set()
[info] scalafix-input / mimaPreviousArtifacts
[info] 	Set()
[info] lambdaJS / mimaPreviousArtifacts
[info] 	Set()
[info] unidocs / mimaPreviousArtifacts
[info] 	Set()
[info] lambdaCloudFormationCustomResourceJVM / mimaPreviousArtifacts
[info] 	Set()
[info] scalafix-tests / mimaPreviousArtifacts
[info] 	Set()
[info] sbtLambda / mimaPreviousArtifacts
[info] 	Set()
[info] examplesJS / mimaPreviousArtifacts
[info] 	Set()
[info] lambdaHttp4sJVM / mimaPreviousArtifacts
[info] 	Set()
[info] examplesJVM / mimaPreviousArtifacts
[info] 	Set()
[info] scalafix-rules / mimaPreviousArtifacts
[info] 	Set()
[info] lambdaHttp4sJS / mimaPreviousArtifacts
[info] 	Set()
[info] mimaPreviousArtifacts
[info] 	Set()
```

@armanbilge do you have any thoughts?

**Comment by armanbilge** [comment]
Yes, because we bumped the base version so that we could make breaking changes :)
https://github.com/typelevel/feral/blob/fa51e2f5aa7a082536a4a71e5375343a7c2d72f4/build.sbt#L21

We have yet to make an v0.3.0 release when bincompat checking will kick-in again.

**Comment by bpholt** [comment]
Oh, of course 🤦🏻‍♂️

For some reason I was thinking we'd already made the `v0.3` release.

Thanks!
