### ISSUE TITLE
Use `Instant` for modeling timestamps

### ISSUE THREAD

**Issue by armanbilge** [typelevel/feral#80]
AKA how do we feel about a scala-java-time dependency.

Pros:
- `Instant` is most idiomatic representation of a timestamp

Cons:
- Bloats generated JS

Mitigation:
- Estimated to be a 120 kb dependency in https://github.com/http4s/http4s-dom/issues/30#issuecomment-954316532
- JS size is not as a big a deal for Node.js lambda compared to browser.
- skunk and http4s already bring in this dependency anyway.

**Comment by bpholt** [comment]
I lean towards using `Instant` and including the dependency. 120kb doesn't seem like a big deal for this purpose and having the idiomatic representation will be less confusing for users.

**Comment by kubukoz** [comment]
120kb doesn't seem like much in the scale of 50megs (aws limit)

**Comment by armanbilge** [comment]
Cool, I'd say that's decided :) anyone feel free to PR an update to events with this.
